# Site settings :)
title: Site title!
email: your-email@domain.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Environment (Wetlands) - Engineering - Art"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
# cool earthy
  primary: 7ca982 #behind picture
  primary-rgb: 7ca982 #"128,179,255"
  secondary: 292f36 #top bar and words
  secondary-dark: 292f36 #bottom bar
  # # cool earthy
  # primary: 7ca982 #behind picture
  # primary-rgb: 7ca982 #"128,179,255"
  # secondary: 243e36 #top bar and words
  # secondary-dark: f1f7ed #bottom bar
  ## earthy palette:
  # primary: a7c957 #behind picture
  # primary-rgb: f2e8cf #unk
  # secondary: 6a994e #top bar and words
  # secondary-dark: bc4749 #bottom

# Footer settings
footer:
  copyright: Charlie Weiss
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:title:output_ext"
